name: model-training
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'  # <-- specify your desired Python version here

      - uses: iterative/setup-cml@v1

      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          python app.py
